ApplicationOutage/Controllers/ActivateUsersController.cs
using ApplicationOutage.Models;
using ApplicationOutage.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using PagedList;
using System.Web;
using System.Web.Mvc;
using System.Net;
using ApplicationOutage.Filters;

namespace ApplicationOutage.Controllers
{

    [AdminAuthorize]
    public class ActivateUsersController : Controller
    {
        // GET: ActivateUsers
        //[Authorize(Users ="SuperAdmin")]
        public ActionResult Index(string searchString, int? page)
        {
            UserManager userManager = new UserManager();
            List<UsersViewModel> users; 
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
                users = userManager.GetRegisteredUsers().Where(x=>x.UserEmail.Contains(searchString)).ToList();
            }
            else
            {
                users = userManager.GetRegisteredUsers().ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: ActivateUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserManager userManager = new UserManager();
            UsersViewModel user = userManager.GetUser(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ActivateUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "Password,ConfirmPassword")] UsersViewModel user)
        {
            ModelState.Remove("Password");
            ModelState.Remove("ConfirmPassword");
            if (ModelState.IsValid)
            {
                UserManager userManager = new UserManager();

                if (userManager.EditUser(user))
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Edit");
            }
            return View(user);
        }
    }
}

ApplicationOutage/Controllers/UsersController.cs
using ApplicationOutage.Models;
using ApplicationOutage.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ApplicationOutage.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginUser(LoginModel LoginUser)
        {
            UserManager userManager = new UserManager();
            if (userManager.IsUserActivated(LoginUser))
            {
                FormsAuthentication.SetAuthCookie(LoginUser.UserEmail, false);
              string s =  HttpContext.User.Identity.Name;
               return RedirectToAction("Index", "Outage");
            }
            ViewBag.Message = "Incorrect User Email or Password or your Account not yet activated. Contact to your application administrator.";
               return View("Login");
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterUser(UsersViewModel user)
        {
            if (ModelState.IsValid)
            {
                UserManager userMgr = new UserManager();
                userMgr.RegisterUser(user);
                return RedirectToAction("Login");
            }
            return View("Register");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        public ActionResult ForgotPassword()
        {
            return View("ResetPassword");
        }

        [HttpPost]
        public ActionResult SetUserPassword([Bind(Exclude = "Password,ConfirmPassword")] ForgotPasswordModel user)
        {
            ModelState.Remove("Password");
            ModelState.Remove("ConfirmPassword");
            if (ModelState.IsValid)
            {
                UserManager userManager = new UserManager();
                if (userManager.ResetPassword(user))
                {
                    return RedirectToAction("Login");
                }
            }
            return View("ForgotPassword");
        }
    }
}

ApplicationOutage/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-danger">
    <strong>401 Authorized!</strong> You are not Authorized User to access this Page.
</div>

ApplicationOutage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WK-ITOps Data Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navColor">
        <div class="navbar-header pull-left">
            @if (HttpContext.Current.User.Identity.IsAuthenticated)
            {
                <a href="@Url.Action("Index", "Outage")">
                    <img src="~/Images/Logo.jpg" alt="Site Logo" class="logo" />
                </a>
            }
            else
            {
                <a href="#">
                    <img src="~/Images/Logo.jpg" alt="Site Logo" class="logo" />
                </a>
            }
        </div>
        <div class="container-fluid">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav move70Left">
                        <li>@Html.ActionLink("Outage List", "Index", "Outage", null, htmlAttributes: new { @class = "navTabColor" })</li>
                        <li>@Html.ActionLink("Availability Report", "TotalAvailability", "Availability", null, htmlAttributes: new { @class = "navTabColor" })</li>
                        @if (System.Configuration.ConfigurationManager.AppSettings["AdminUser"].ToUpper() == HttpContext.Current.User.Identity.Name.ToUpper())
                        {
                            <li>@Html.ActionLink("Active User", "Index", "ActivateUsers", null, htmlAttributes: new { @class = "navTabColor" })</li>
                        }
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        <li><a class="navTabColor">Welcome: <span>@HttpContext.Current.User.Identity.Name </span></a></li>
                        <li>@Html.ActionLink("Log Out", "Logout", "Users", null, htmlAttributes: new { @class = "navTabColor" })</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav pull-right">
                        <li>@Html.ActionLink("Log In", "LogIn", "Users", null, htmlAttributes: new { @class = "navTabColor" })</li>
                        <li>@Html.ActionLink("Register", "Register", "Users", null, htmlAttributes: new { @class = "navTabColor" })</li>
                    </ul>
                }

            </div>
        </div>
    </div>
    <div class="body-content container-fluid">
        @RenderBody()
        <hr />
        <footer class="footerBottom">
            <p class="centerText">@DateTime.Now.Year -Wolters kluwer</p>
        </footer>
    </div>
   
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/AppScript")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>