ApplicationOutage/ViewModels/OutageViewModel.cs
using ApplicationOutage.Filters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApplicationOutage.ViewModels
{
    public class OutageViewModel:IValidatableObject
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }

        [Display(Name = "Start Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Start Date is required.")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "End Date is required.")]
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Impact is required.")]
        public string Impact { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Component is required.")]
        public string Component { get; set; }

        [Display(Name = "Incident #")]
        [Required(ErrorMessage = "Incident Number is required.")]
        public string IncidentNumber { get; set; }
        [Display(Name = "Application Name")]
        public string ApplicationName { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var results = new List<ValidationResult>();

            if (StartDate > EndDate)
                results.Add(new ValidationResult("End Date cannot be less than Start Date."));

            return results;
        }
    }
}

ApplicationOutage/Controllers/OutageController.cs
using ApplicationOutage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using OfficeOpenXml;
using ApplicationOutage.Filters;
using ApplicationOutage.ViewModels;

namespace ApplicationOutage.Controllers
{
    [CustomAuthorize]
    public class OutageController : Controller
    {
        // GET: Outage
        public ActionResult Index(string searchString, int? page)
        {
            OutageManager outageManager = new OutageManager();
            List<Outage> outages;
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
                outages = outageManager.GetOutages().Where(x => !string.IsNullOrEmpty(x.IncidentNumber) && x.IncidentNumber.ToLower().Contains(searchString.ToLower())).ToList();
            }
            else
            {
                outages = outageManager.GetOutages();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(outages.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Add()
        {
            ApplicationManager applicationManager = new ApplicationManager();
            ViewBag.Applications = applicationManager.GetApplicationList().Select(x => new SelectListItem { Text = x.ApplicationName, Value = x.ID.ToString() });
            ViewBag.Components = Components.GetComponents();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "ID,ApplicationID,StartDate,EndDate,IncidentNumber,Impact,Description,Component")] OutageViewModel outage)
        {
            if (ModelState.IsValid)
            {
                OutageManager outageManager = new OutageManager();
                if (outageManager.AddOutage(outage))
                {
                    return RedirectToAction("Index");
                }
            }
            return View(outage);
        }

        // GET: Outages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutageManager outageManager = new OutageManager();
            OutageViewModel outage = outageManager.GetOutage(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            return View(outage);
        }

        // GET: Outages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutageManager outageManager = new OutageManager();
            OutageViewModel outage = outageManager.GetOutage(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            ApplicationManager appManager = new ApplicationManager();
            ViewBag.ApplicationID = new SelectList(appManager.GetApplicationList(), "ID", "ApplicationName", outage.ApplicationID);
            ViewBag.Components = Components.GetComponents();
            return View(outage);
        }

        // POST: Outages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ApplicationID,StartDate,EndDate,IncidentNumber,Impact,Description,Component")] OutageViewModel outage)
        {
            if (ModelState.IsValid)
            {
                OutageManager outageManager = new OutageManager();

                if (outageManager.EditOutage(outage))
                {
                    return RedirectToAction("Index");
                }


                return RedirectToAction("Index");
            }
            // ViewBag.ApplicationID = new SelectList(db.Applications, "ID", "ApplicationName", outage.ApplicationID);
            return View(outage);
        }

        // GET: Outages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutageManager outageManager = new OutageManager();
            OutageViewModel outage = outageManager.GetOutage(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            return View(outage);
        }

        // POST: Outages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OutageManager outageManager = new OutageManager();
            outageManager.DeleteOutage(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public bool GetIncidents(string IncidentNumber)
        {
            OutageManager outageManager = new OutageManager();
           return outageManager.GetIncident(IncidentNumber);
        }

        [HttpPost]
        public FileStreamResult ExportToExcel()
        {
            OutageManager outageManager = new OutageManager();
            var result = outageManager.GetOutages();
            if (result.Any())
            {
                string fileName = DateTime.Now.ToString("MM_dd_yyyy_HH_mm_ss") + "_IncidenReport.xlsx";
                var serverPath = HttpContext.Server.MapPath("~/Downloads/");
                DirectoryInfo outputDir = new DirectoryInfo(serverPath);
                FileInfo file = new FileInfo(outputDir.FullName + fileName);

                MemoryStream MS = new MemoryStream();
                using (ExcelPackage package = new ExcelPackage(file))
                {
                    ExcelWorksheet ws = package.Workbook.Worksheets.Add("Outage Data");

                    // Set Header.
                    ws.Cells["A1"].Value = "Application Name";
                    ws.Cells["B1"].Value = "Start Date";
                    ws.Cells["C1"].Value = "End Date";
                    ws.Cells["D1"].Value = "Total Outage(Min)";
                    ws.Cells["E1"].Value = "Impact";
                    ws.Cells["F1"].Value = "Incident Number";
                    ws.Cells["G1"].Value = "Description";
                    ws.Cells["H1"].Value = "Component";
                    ws.Cells["A1:H1"].Style.Font.Bold = true;

                    // Set color to headers.
                    ws.Cells["A1:H1"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    ws.Cells["A1:H1"].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Silver);
                    ws.Cells["A1:H1"].Style.VerticalAlignment = OfficeOpenXml.Style.ExcelVerticalAlignment.Center;

                    // set style to header cells.
                    ws.Cells["A1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["B1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["C1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["D1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["E1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["F1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["G1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                    ws.Cells["H1"].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);

                    // Write data here...
                    int rowCount = 2;
                    int colCount = 0;
                    foreach (var item in result)
                    {
                        colCount = 1;
                        ws.Cells[rowCount, colCount].Value = item.Application.ApplicationName;
                        ws.Cells[rowCount, ++colCount].Value = item.StartDate;
                        ws.Cells[rowCount, colCount].Style.Numberformat.Format = "dd/MM/yyyy HH:mm";
                        ws.Cells[rowCount, ++colCount].Value = item.EndDate;
                        ws.Cells[rowCount, colCount].Style.Numberformat.Format = "dd/MM/yyyy HH:mm";
                        ws.Cells[rowCount, ++colCount].Value = (item.EndDate-item.StartDate).TotalMinutes;
                        ws.Cells[rowCount, ++colCount].Value = item.Impact;
                        ws.Cells[rowCount, colCount].Style.Numberformat.Format = "#0\\.00%";
                        ws.Cells[rowCount, ++colCount].Value = item.IncidentNumber;
                        ws.Cells[rowCount, ++colCount].Value = item.Description;
                        ws.Cells[rowCount, ++colCount].Value = item.Component;

                        // set style here.
                        for (int i = 1; i <= colCount; i++)
                        {
                            ws.Cells[rowCount, i].Style.Border.BorderAround(OfficeOpenXml.Style.ExcelBorderStyle.Thin);
                        }
                        rowCount++;
                    }
                    ws.Cells[ws.Dimension.Address].AutoFitColumns();
                    package.SaveAs(MS);
                }
                MS.Position = 0;
                var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                FileStreamResult FSR = new FileStreamResult(MS, contentType);
                FSR.FileDownloadName = fileName;
                return FSR;
            }
            return null;
        }

        public FileStreamResult Import()
        {
            return null;
        }
    }
}

ApplicationOutage/Views/Outage/Add.cshtml
@using System.Web.Mvc.Html;
@model ApplicationOutage.ViewModels.OutageViewModel

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="~/Scripts/jquery.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>

<h2 class="centerText">New Outage</h2>

@using (Html.BeginForm("Save", "Outage", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationID, "Application Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationID", (IEnumerable<SelectListItem>)ViewBag.Applications, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate,"Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            <div>
                <span id="errormess" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IncidentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IncidentNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IncidentNumber, "", new { @class = "text-danger" })
            <div>
                <span id="errorIncident" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Impact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Impact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Impact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Component, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var component in ViewBag.Components)
            {
                string value = component.Value;
                <div>
                    <lable>
                        @Html.RadioButtonFor(model => model.Component, value)
                        @component.Value
                    </lable>
                </div>
            }
            @Html.ValidationMessageFor(model => model.Component, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnOutage" type="submit" value="Add Outage" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#StartDate,#EndDate").datetimepicker({
                format: 'd-m-Y H:i',
                step: 05
            });
        });
    });
</script>

ApplicationOutage/Views/Outage/Delete.cshtml
@model ApplicationOutage.ViewModels.OutageViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Outage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Impact)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Impact)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IncidentNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IncidentNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Component)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Component)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplicationOutage/Views/Outage/Details.cshtml
@model ApplicationOutage.ViewModels.OutageViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Outage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Impact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Impact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Component)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Component)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplicationOutage/Views/Outage/Edit.cshtml
@model ApplicationOutage.ViewModels.OutageViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="~/Scripts/jquery.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<h2 class="centerText">Outage Update</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationID, "ApplicationID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate,new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            <div>
                <span id="errormess" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IncidentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IncidentNumber, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IncidentNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Impact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Impact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Impact, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Component, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var component in ViewBag.Components)
            {
                string value = component.Value;
                <lable>
                    @Html.RadioButtonFor(model => model.Component, value)
                    @component.Value
                </lable>
                @Html.ValidationMessageFor(model => model.Component, "", new { @class = "text-danger" })
            }

        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnOutage" type="submit" value="Save" class="btn btn-success btn-sm" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#StartDate,#EndDate").datetimepicker({
                format: 'd-m-Y H:i',
                step: 05
            });
        });
    });
</script>

ApplicationOutage/Views/Outage/Index.cshtml
@model PagedList.IPagedList<ApplicationOutage.Outage>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Incident Report";
}

<h2 class="centerText">Incident Report</h2>
<div class="col-sd-12">
    <div class="col-sm-4">
        @using (Html.BeginForm())
        {
            <p class="pull-right">
                Find by Incident #: @Html.TextBox("SearchString")
                <input type="submit" value="Search" class="btn btn-success btn-sm" />
            </p>
        }
    </div>
    <div class="col-sm-1">
        @using (Html.BeginForm("ExportToExcel", "Outage", FormMethod.Post))
        {
            <p class="pull-left">
                <input type="submit" value="Export To Excel" class="btn btn-info btn-sm" />
            </p>
        }
    </div>
    <div class="col-sm-1">
        <p class="pull-left move15Left">
            <input type="button" value="Create New" class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Add", "Outage")'" />
        </p>
    </div>

    <div class="col-sm-1">
        @using (Html.BeginForm("Import", "Outage", FormMethod.Post))
        {
            <p class="pull-left">
                <input type="submit" value="Import" class="btn btn-default btn-sm" />
            </p>
        }
    </div>

</div>
<table class="table table-bordered table-condensed table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayName("Start Date")
        </th>
        <th>
            @Html.DisplayName("End Date")
        </th>
        <th>
            @Html.DisplayName("Total Outage")
        </th>
        <th>
            @Html.DisplayName("Impact")
        </th>
        <th>
            @Html.DisplayName("Incident Number")
        </th>
        <th>
            @Html.DisplayName("Description")
        </th>
        <th>
            @Html.DisplayName("Component")
        </th>
        <th>
            @Html.DisplayName("Application Name")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>

                @{
                    double min = (item.EndDate - item.StartDate).TotalMinutes;
                }
                @min
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Impact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IncidentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Component)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Application.ApplicationName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>
<hr/>
<br/>
<div class="pager">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
         @Html.PagedListPager(Model, page => Url.Action("Index", new { page}))
</div>